package biz.brighta.obdandroid;

    public class PIDs {

        static final short PID_REQUEST        = 0x740;  // 0x7DF
        static final short PID_REPLY          = 0x300;  // 0x7E0

        static final byte PID_0_20            = 0x00;   // PID 0x00 - 0x20 supported
        static final byte STATUS_DTC          = 0x01;   // Status since DTC Cleared
        static final byte FREEZE_DTC          = 0x02;   // Freeze Diagnostic Trouble Code
        static final byte FUEL_STATUS         = 0x03;   // Fuel System Status
        static final byte ENGINE_LOAD         = 0x04;   // Calculated Engine Load
        static final byte ENGINE_COOLANT_TEMP = 0x05;   // Engine Coolant Temperature
        static final byte ST_FUEL_TRIM_1      = 0x06;   // Short Term Fuel % Trim - Bank 1
        static final byte LT_FUEL_TRIM_1      = 0x07;   // Long Term Fuel % Trim - Bank 1
        static final byte ST_FUEL_TRIM_2      = 0x08;   // Short Term Fuel % Trim - Bank 2
        static final byte LT_FUEL_TRIM_2      = 0x09;   // Long Term Fuel % Trim - Bank 2
        static final byte FUEL_PRESSURE       = 0x0A;   // Fuel Pressure
        static final byte INTAKE_PRESSURE     = 0x0B;   // Intake Manifold Absolute Pressure
        static final byte ENGINE_RPM          = 0x0C;   // Engine RPM
        static final byte VEHOICLE_SPEED      = 0x0D;   // Vehicle speed
        static final byte TIMING_ADVANCE      = 0x0E;   // Timing Advance
        static final byte INTAKE_TEMP         = 0x0F;   // Intake Air Temperature
        static final byte MAF_SENSOR          = 0x10;   // MAF Sensor Air Flow Rate
        static final byte THROTTLE            = 0x11;   // Throttle Position
        static final byte COMMANDED_SEC_AIR   = 0x12;   // Commanded Secondary Air Status
        static final byte O2_SENS_PRES        = 0x13;   // Detected O2 Sensors
        static final byte O2_B1S1_VOLTAGE     = 0x14;   // O2 Sensor Voltage - Bank 1 Sensor 1
        static final byte O2_B1S2_VOLTAGE     = 0x15;   // O2 Sensor Voltage - Bank 1 Sensor 2
        static final byte O2_B1S3_VOLTAGE     = 0x16;   // O2 Sensor Voltage - Bank 1 Sensor 3
        static final byte O2_B1S4_VOLTAGE     = 0x17;   // O2 Sensor Voltage - Bank 1 Sensor 4
        static final byte O2_B2S1_VOLTAGE     = 0x18;   // O2 Sensor Voltage - Bank 2 Sensor 1
        static final byte O2_B2S2_VOLTAGE     = 0x19;   // O2 Sensor Voltage - Bank 2 Sensor 2
        static final byte O2_B2S3_VOLTAGE     = 0x1A;   // O2 Sensor Voltage - Bank 2 Sensor 3
        static final byte O2_B2S4_VOLTAGE     = 0x1B;   // O2 Sensor Voltage - Bank 2 Sensor 4
        static final byte OBDII_STANDARDS     = 0x1C;   // List of OBDII Standars the car conforms to
        static final byte O2_SENS_PRES_ALT    = 0x1D;   // Detected O2 Sensors - Alternate Grouping
        static final byte AUX_IN_STATUS       = 0x1E;   // Auxiliary Input Status
        static final byte ENGINE_RUNTIME      = 0x1F;   // Run Time Since Engine Started
        static final byte PID_21_40           = 0x20;   // PID 0x21 - 0x40 supported
        static final byte DIST_TRAVELED_MIL   = 0x21;   // Distance Traveled with MIL On
        static final byte FUEL_RAIL_PRESSURE  = 0x22;   // Fuel Rail Pressure Relative to Manifold
        static final byte FUEL_RAIL_PRES_ALT  = 0x23;   // MPI/Diesel Fuel Rail Pressure
        static final byte O2S1_WR_LAMBDA_V    = 0x24;   // O2 Sensor 1 Equivalence Ratio Voltage
        static final byte O2S2_WR_LAMBDA_V    = 0x25;   // O2 Sensor 2 Equivalence Ratio Voltage
        static final byte O2S3_WR_LAMBDA_V    = 0x26;   // O2 Sensor 3 Equivalence Ratio Voltage
        static final byte O2S4_WR_LAMBDA_V    = 0x27;   // O2 Sensor 4 Equivalence Ratio Voltage
        static final byte O2S5_WR_LAMBDA_V    = 0x28;   // O2 Sensor 5 Equivalence Ratio Voltage
        static final byte O2S6_WR_LAMBDA_V    = 0x29;   // O2 Sensor 6 Equivalence Ratio Voltage
        static final byte O2S7_WR_LAMBDA_V    = 0x2A;   // O2 Sensor 7 Equivalence Ratio Voltage
        static final byte O2S8_WR_LAMBDA_V    = 0x2B;   // O2 Sensor 8 Equivalence Ratio Voltage
        static final byte COMMANDED_EGR       = 0x2C;   // Commanded EGR
        static final byte EGR_ERROR           = 0x2D;   // EGR Error
        static final byte COMMANDED_EVAP_P    = 0x2E;   // Commanded Evaporative Purge
        static final byte FUEL_LEVEL          = 0x2F;   // Fuel Level Input
        static final byte WARMUPS_SINCE_CLR   = 0x30;   // Number of Warmups since DTC Cleared
        static final byte DIST_SINCE_CLR      = 0x31;   // Distance Traveled Since DTC Cleared
        static final byte EVAP_PRESSURE       = 0x32;   // Evap. System Vapor Pressure
        static final byte BAROMETRIC_PRESSURE = 0x33;   // Barometric Pressure
        static final byte O2S1_WR_LAMBDA_I    = 0x34;   // O2 Sensor 1 Equivalence Ratio Current
        static final byte O2S2_WR_LAMBDA_I    = 0x35;   // O2 Sensor 2 Equivalence Ratio Current
        static final byte O2S3_WR_LAMBDA_I    = 0x36;   // O2 Sensor 3 Equivalence Ratio Current
        static final byte O2S4_WR_LAMBDA_I    = 0x37;   // O2 Sensor 4 Equivalence Ratio Current
        static final byte O2S5_WR_LAMBDA_I    = 0x38;   // O2 Sensor 5 Equivalence Ratio Current
        static final byte O2S6_WR_LAMBDA_I    = 0x39;   // O2 Sensor 6 Equivalence Ratio Current
        static final byte O2S7_WR_LAMBDA_I    = 0x3A;   // O2 Sensor 7 Equivalence Ratio Current
        static final byte O2S8_WR_LAMBDA_I    = 0x3B;   // O2 Sensor 8 Equivalence Ratio Current
        static final byte CAT_TEMP_B1S1       = 0x3C;   // Catalyst Temperature Bank 1 Sensor 1
        static final byte CAT_TEMP_B1S2       = 0x3E;   // Catalyst Temperature Bank 1 Sensor 2
        static final byte CAT_TEMP_B2S1       = 0x3D;   // Catalyst Temperature Bank 2 Sensor 1
        static final byte CAT_TEMP_B2S2       = 0x3F;   // Catalyst Temperature Bank 2 Sensor 2
        static final byte PID_41_60           = 0x40;   // PID 0x41 - 0x60 supported
        static final byte MONITOR_STATUS      = 0x41;   // Monitor Status This Drive Cycle
        static final byte ECU_VOLTAGE         = 0x42;   // Control Module Voltage
        static final byte ABSOLUTE_LOAD       = 0x43;   // Absolute Load Value
        static final byte COMMANDED_EQUIV_R   = 0x44;   // Commanded Equivalence Ratio
        static final byte REL_THROTTLE_POS    = 0x45;   // Relative Throttle Position
        static final byte AMB_AIR_TEMP        = 0x46;   // Ambient Air Temperature
        static final byte ABS_THROTTLE_POS_B  = 0x47;   // Absolute Throttle Position B
        static final byte ABS_THROTTLE_POS_C  = 0x48;   // Absolute Throttle Position C
        static final byte ACCEL_POS_D         = 0x49;   // Accelerator Pedal Position D
        static final byte ACCEL_POS_E         = 0x4A;   // Accelerator Pedal Position E
        static final byte ACCEL_POS_F         = 0x4B;   // Accelerator Pedal Position F
        static final byte COMMANDED_THROTTLE  = 0x4C;   // Commanded Throttle Actuator
        static final byte TIME_RUN_WITH_MIL   = 0x4D;   // Time Run with MIL on
        static final byte TIME_SINCE_CLR      = 0x4E;   // Time Since DTC Cleared
        static final byte MAX_R_O2_VI_PRES    = 0x4F;   // Maximum Value - Equivalence ratio, O2 Voltage, O2 Current, Intake Manifold Pressure
        static final byte MAX_AIRFLOW_MAF     = 0x50;   // Maximum MAF Airflow Value
        static final byte FUEL_TYPE           = 0x51;   // Fuel Type
        static final byte ETHANOL_PERCENT     = 0x52;   // Ethanol fuel %
        static final byte ABS_EVAP_SYS_PRES   = 0x53;   // absolute Evap. System Vapor Pressure
        static final byte EVAP_SYS_PRES       = 0x54;   // Evap. System Vapor Pressure
        static final byte ST_O2_TRIM_B1B3     = 0x55;   // Short Term Secondary O2 Sensor Trim - Bank 1 and 3
        static final byte LT_O2_TRIM_B1B3     = 0x56;   // Long Term Secondary O2 Sensor Trim - Bank 1 and 3
        static final byte ST_02_TRIM_B2B4     = 0x57;   // Short Term Secondary O2 Sensor Trim - Bank 2 and 4
        static final byte LT_O2_TRIM_B2B4     = 0x58;   // Long Term Secondary O2 Sensor Trim - Bank 2 and 4
        static final byte ABS_FUEL_RAIL_PRES  = 0x59;   // Absolute Fuel Rail Pressure
        static final byte REL_ACCEL_POS       = 0x5A;   // Relative Accelerator Pedal Position
        static final byte HYBRID_BATT_PCT     = 0x5B;   // Hybrid Battery Pack Charge Percent
        static final byte ENGINE_OIL_TEMP     = 0x5C;   // Engine Oil Temperature
        static final byte FUEL_TIMING         = 0x5D;   // Fuel Injection Timing
        static final byte FUEL_RATE           = 0x5E;   // Engine Fuel Rate
        static final byte EMISSIONS_STANDARD  = 0x5F;   // Emmissions Requirements
        static final byte DEMANDED_TORQUE     = 0x61;   // Driver's Demanded Torque - Percent
        static final byte ACTUAL_TORQUE       = 0x62;   // Actual Engine Torque - Percent
        static final byte REFERENCE_TORQUE    = 0x63;   // Engine Reference Torque
        static final byte ENGINE_PCT_TORQUE   = 0x64;   // Engine Percent Torque
        static final byte AUX_IO_SUPPORTED    = 0x65;   // Auxiliary Input/Output Supported

        static final byte P_MAF_SENSOR        = 0x66;    //
        static final byte P_ENGINE_COOLANT_T  = 0x67;    //
        static final byte P_INTAKE_TEMP       = 0x68;    //
        static final byte P_COMMANDED_EGR     = 0x69;    //
        static final byte P_COMMANDED_INTAKE  = 0x6A;    //
        static final byte P_EGR_TEMP          = 0x6B;    //
        static final byte P_COMMANDED_THROT   = 0x6C;    //
        static final byte P_FUEL_PRESSURE     = 0x6D;    //
        static final byte P_FUEL_INJ_PRES     = 0x6E;    //
        static final byte P_TURBO_PRESSURE    = 0x6F;    //
        static final byte P_BOOST_PRES_CONT   = 0x70;    //
        static final byte P_VGT_CONTROL       = 0x71;    //
        static final byte P_WASTEGATE_CONT    = 0x72;    //
        static final byte P_EXHAUST_PRESSURE  = 0x73;    //
        static final byte P_TURBO_RPM         = 0x74;    //
        static final byte P_TURBO_TEMP1       = 0x75;    //
        static final byte P_TURBO_TEMP2       = 0x76;    //
        static final byte P_CACT              = 0x77;    //
        static final byte P_EGT_B1            = 0x78;    //
        static final byte P_EGT_B2            = 0x79;    //
        static final byte P_DPF1              = 0x7A;    //
        static final byte P_DPF2              = 0x7B;    //
        static final byte P_DPF_TEMP          = 0x7C;    //
        static final byte P_NOX_NTE_STATUS    = 0x7D;    //
        static final byte P_PM_NTE_STATUS     = 0x7E;    //
        static final byte P_ENGINE_RUNTUME    = 0x7F;    //
        static final short P_ENGINE_AECD_1    = 0x81;    //
        static final short P_ENGINE_AECD_2    = 0x82;    //
        static final short P_NOX_SENSOR       = 0x83;    //
        static final short P_MANIFOLD_TEMP    = 0x84;    //
        static final short P_NOX_SYSTEM       = 0x85;    //
        static final short P_PM_SENSOR        = 0x86;    //
        static final short P_IN_MANIF_TEMP    = 0x87;    //


}
